# Site settings
title: notickethome
tagline: Heading off round the world with a one way ticket to India
description: >
  Heading off round the world with a one way ticket to India.
url: "http://notickethome.co.uk"
instagram_username: notickethome

# Build settings
markdown: kramdown
