# Site settings
title: Andrew Carter
tagline: Programming, Photography, Travel and Science
description: >
  Passionate about programming, photography, travel and science.
url: "https://andrew.carterlunn.co.uk"
twitter_username: AndrewCarterUK
github_username: AndrewCarterUK

# Build settings
markdown: kramdown

collections:
  drafts:
    output: true
