# Site settings
title: Andrew Carter
tagline: Programming, Photography, Travel and Science
description: >
  Passionate about programming, photography, travel and science.
url: "http://andrew.carterlunn.co.uk"
twitter_username: AndrewCarterUK
github_username:  AndrewCarterUK

# Build settings
markdown: kramdown
