var app=angular.module("caterhamApp",[])
app.factory("state",[function(){return{view:"model",model:270,pack:"7"}}]),app.factory("logic",["state","sections","packs","models",function(t,o,e,n){return{modelCost:function(){for(var o,e=0;e<n.length;e++)n[e].number==t.model&&(o=n[e])
return o.cost},packCost:function(){if("7"==t.pack)return 0
for(var o,n=0;n<e.length;n++)e[n].name==t.pack&&(o=e[n])
return o.cost},optionsCost:function(){for(var e=0,n=0;n<o.length;n++)for(var c=o[n],s=0;s<c.options.length;s++){var a=c.options[s],r=a.choices[a.chosen]
r.map.hasOwnProperty(t.pack)&&(e+=r.map[t.pack])}return e},filter:function(){for(var e=0;e<o.length;e++)for(var n=o[e],c=0;c<n.options.length;c++){var s=n.options[c],a=s.choices[s.chosen]
a.map.hasOwnProperty(t.pack)&&null!==a.map[t.pack]||(s.chosen=0)
for(var r=0;r<s.choices.length;r++){var i=s.choices[r]
i.map.hasOwnProperty(t.pack)&&0===i.map[t.pack]&&(s.chosen=r)}}}}}]),app.controller("FooterController",["$scope","state","logic",function(t,o,e){t.state=o,t.logic=e}]),app.controller("ProgressController",["$scope","state",function(t,o){t.state=o,t.select=function(o){t.state.view=o,setTimeout(function(){$(window).resize()},1)}}]),app.controller("ModelController",["$scope","state","models",function(t,o,e){t.state=o,t.select=function(o){t.state.model=o,t.state.view="pack",setTimeout(function(){$(window).resize()},1)},t.models=e}]),app.controller("PackController",["$scope","state","packs","logic",function(t,o,e,n){t.state=o,t.select=function(o){var e=t.state.pack!==o
t.state.pack=o,t.state.view="options",e&&n.filter()},t.packs=e}]),app.controller("SummaryController",["$scope","state","logic","sections",function(t,o,e,n){t.state=o,t.logic=e,t.sections=n}]),app.controller("OptionsController",["$scope","state","sections",function(t,o,e){t.state=o,t.choose=function(t,o){o.chosen=t},t.isChosen=function(t,o){return o.chosen==t},t.isDisabled=function(o,e){return!e.choices[o].map.hasOwnProperty(t.state.pack)||null===e.choices[o].map[t.state.pack]},t.isStandard=function(o){return o.standardOn.indexOf(t.state.model)!=-1},t.isAvailable=function(o){return o.availableFor.indexOf(t.state.model)!=-1},t.sectionIndex=0,t.moveSection=function(o){t.sectionIndex=o},t.isSection=function(o){return t.sectionIndex==o},t.sections=e}])
